INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGETED_DATE, DONE)
SELECT 1, 'admin', 'Go to University', TO_DATE('2030-12-09', 'YYYY-MM-DD'), 0
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TODO);

INSERT INTO DISTRICT (ID,B_NAME,E_NAME)
SELECT 1, 'Dhaka', 'Dhake'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DISTRICT);
